<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0;net472</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>CodiceFiscale</PackageId>
    <Version>1.0.1</Version>
    <Authors>Lorenzo Maiuri</Authors>
    <Description>
        A comprehensive library for handling the Italian Tax Code (Codice Fiscale). This package allows encoding, decoding, and validation of Codice Fiscale, including support for omocode resolution. Ideal for developers working with Italian identification systems and tax code management.
    </Description>
    <PackageTags>codice-fiscale; codice_fiscale; Codice Fiscale; Italian Tax Code; Italy; validation; omocode</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/lorenzomaiuri-dev/CodiceFiscale</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net472'">
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>



  <ItemGroup>
    <None Update="data/countries.json" Pack="true" PackagePath="contentFiles\any\any;content">
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data/deleted-countries.json" Pack="true" PackagePath="contentFiles\any\any;content">
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data/municipalities.json" Pack="true" PackagePath="contentFiles\any\any;content">
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Include="../LICENSE" Pack="true" PackagePath="/" />
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
